#!/usr/bin/env bash
# This script pings an IP address 5 times, passed as an argument.

# Check if an IP address is provided as an argument
if [ -z "$1" ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi

# Ping the IP address 5 times
ping -c 5 "$1"

