#!/usr/bin/env bash
# Check for IP argument and display usage if missing
if [ -z "$1" ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi
# Ping the specified IP address 5 times
ping -c 5 "$1"

