#!/usr/bin/env bash
#localhost resolves to 127.0.0.2 & facebook.com resolves to 8.8.8.8

sudo bash -c 'echo -e "127.0.0.2 localhost" > /etc/hosts'
sudo bash -c 'echo -e "8.8.8.8 facebook.com" >> /etc/hosts'
